---
title: BespaarMaar
timezone: Europe/Amsterdam
volledige-titel: BespaarMaar
image_src: "/assets/img/image_src.png"
logo: "/assets/img/image_src.png"
keywords: Bespaar, Vergelijk, Bespaartips, Zorgverzekering, Energie, Geld verdienen, Inkomen, Budget 
exclude:
- vendor
description: BespaarMaar geeft je tips over besparen en helpt helpt je met het vergelijken van verzekering, abonnementen, etc âœ… 
    Wij bieden een groot aantal verschillende onafhankelijke vergelijkings tools aan die je kunt gebruiken om de beste leverancier te vinden. 
theme_color: "#fb5353"
baseurl: 
collections:
  posts:
    title: Posts
    output: true
    permalink: /blog/:title
defaults:
- scope:
    path: ''
  values:
    image: ''
    description: ''
    title: ''
    layout: default
- scope:
    path: ''
    type: posts
  values:
    image: ''
    description: ''
    title: ''
    layout: post
abbrv: ESS
dribbble_username: es_studio
facebook_username: ES-Studio-2052606714783317
flickr_username: es_studio
github_username: LesterGallagher
instagram_username: 
linkedin_username: 
pinterest_username: eestudio0040
twitter_username: esstudio_site
youtube_username: 9Wereld
googleplus_username: 
rss: true
facebook:
  app_id: 1015809515263840
  publisher: 2052606714783317
  admins: 100028399686104
webmaster_verifications:
  google: 
  bing: 
  alexa: 
  yandex: 
  baidu: 
twitter:
  username: esstudio_site
sass:
  style: compressed
  sass_dir: _sass
url: https://bespaarmaar.esstudio.site
enforce_ssl: bespaarmaar.esstudio.site
plugins:
- jekyll-sitemap
- jekyll-seo-tag
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
theme: minima
author: Sem Postma
designer: Sem Postma
lang: en
humanstxt_author:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
humanstxt_designer:
  name: Sem Postma
  from: Oosterhout, Noord Brabant, The Netherlands
  role: Developer
  email: sem.postma@gmail.com
google_analytics: UA-90014538-4
